<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Shank -->
  <xacro:macro name="anymal_shank" params="leg:=^ mesh_name **properties">

    <!-- Xacro:Properties -->
    <xacro:insert_block name="properties"/>

    <!-- Shank link -->
    <xacro:property name="left"  value="${int(leg.startswith('L'))*2-1}"/>
    <xacro:property name="front" value="${int(leg.startswith('F', 1))*2-1}"/>
    <link name="${leg}_SHANK">
      <xacro:if value="$(arg mesh)">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 ${(front-1)*0.5*PI}"/>
          <geometry>
            <mesh filename="${mesh_name}"
                  scale="${anymal_meshes_scale}"/>
          </geometry>
        </visual>
      </xacro:if>
      <xacro:unless value="$(arg mesh)">
        <visual>
          <origin xyz="${front*0.04} ${-left * 0.02} -0.04" rpy="0 ${-front * 0.9} ${front * left * -0.2}"/>
          <geometry>
            <cylinder radius="${fabs(collision_r_s)}" length="0.13"/>
          </geometry>
          <material name="anymal_material" />
        </visual>
        <visual>
          <origin xyz="${front * 0.06} ${left * -0.03} -0.18" rpy="${-left * 0.0} ${front * 0.34} 0"/>
          <geometry>
            <cylinder radius="${fabs(collision_r_s)}" length="0.19"/>
          </geometry>
          <material name="anymal_material" />
        </visual>
      </xacro:unless>
      <collision>
        <origin xyz="${front*0.04} ${left * -0.02} -0.04" rpy="0 ${-front * 0.9} ${front * left * -0.2}"/>
        <geometry>
          <cylinder radius="${fabs(collision_r_s)}" length="0.13"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="${front * 0.06} ${left * -0.03} -0.18" rpy="${-left * 0.0} ${front * 0.34} 0"/>
        <geometry>
          <cylinder radius="${fabs(collision_r_s)}" length="0.19"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="${front*S_r_SScom_x} ${left*S_r_SScom_y} ${S_r_SScom_z}"
                rpy="0 0 0"/>
          <mass value="${m_S}"/>
          <inertia ixx="${S_Ixx_S}" ixy="${front*left*S_Ixy_S}" ixz="${front*S_Ixz_S}"
                   iyy="${S_Iyy_S}" iyz="${left*S_Iyz_S}" izz="${S_Izz_S}"/>
      </inertial>
    </link>

    <!-- Shank joint -->
    <joint name="${leg}_KFE" type="revolute">
      <parent link="${leg}_THIGH"/>
      <child link="${leg}_SHANK"/>
      <origin xyz="${front*T_r_TS_x} ${left*T_r_TS_y} ${T_r_TS_z}"/>
      <axis xyz="0 1 0"/>
      <limit effort="${t_kfe}"
             command_effort="${t_kfe_command}"
             gear_velocity="${gear_velocity}"
             current="${current}"
             lower="${-(front+1)*0.5*s_kfe_1 + (front-1)*0.5*s_kfe_2}"
             upper="${-(front-1)*0.5*s_kfe_1 + (front+1)*0.5*s_kfe_2}"
             velocity="${v_kfe}" />
      <dynamics damping="${d_kfe}" friction="${f_kfe}"/>
    </joint>

    <!-- Foot mount link -->
    <link name="${leg}_FOOT_MOUNT" />

    <!-- Foot mount joint / ankle -->
    <joint name="${leg}_ANKLE_JOINT" type="fixed">
      <parent link="${leg}_SHANK"/>
      <child link="${leg}_FOOT_MOUNT"/>
      <origin xyz="${front*S_r_SM_x} ${left*S_r_SM_y} ${S_r_SM_z}"
              rpy="${left*q_SM_roll} ${front*q_SM_pitch} 0"/>
    </joint>
  </xacro:macro>


</robot>
