<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="anymal_foot" params="leg:=LF">

    <xacro:property name="S_r_SF_x"               value="0.087950"/> <!-- [m] -->
    <xacro:property name="S_r_SF_y"               value="0.013050"/> <!-- [m] -->
    <xacro:property name="S_r_SF_z"               value="-0.33797"/> <!-- [m] shank to foot bottom (0.35) - 0.75*collision_foot_r -->
    <xacro:property name="m_F"                    value="0.25"/> <!-- [kg] -->
    <xacro:property name="F_r_FFcom_x"            value="0.009480"/> <!-- [m] -->
    <xacro:property name="F_r_FFcom_y"            value="-0.00948"/> <!-- [m] -->
    <xacro:property name="F_r_FFcom_z"            value="0.146800"/> <!-- [m] -->
    <xacro:property name="F_Ixx_F"                value="0.00317174097"/> <!-- [kg * m^2] -->
    <xacro:property name="F_Iyy_F"                value="0.00317174092"/> <!-- [kg * m^2] -->
    <xacro:property name="F_Izz_F"                value="0.00008319196"/> <!-- [kg * m^2] -->
    <xacro:property name="F_Ixy_F"                value="0.00000263048"/> <!-- [kg * m^2] -->
    <xacro:property name="F_Ixz_F"                value="0.00006815581"/> <!-- [kg * m^2] -->
    <xacro:property name="F_Iyz_F"                value="0.00006815583"/> <!-- [kg * m^2] -->
    <xacro:property name="collision_foot_r"       value="0.03"/> <!-- [m] -->
    <xacro:property name="collision_adapter_r"    value="0.0175"/> <!-- [m] --> <!-- measured -->
    <xacro:property name="collision_adapter_l"    value="0.282504"/> <!-- [m] -->
    <xacro:property name="leg_config"             value="xx"/> <!-- Leg configurations: xx (knees bent inwards), xo (knees bent backwards) -->

    <!-- Generated properties -->
    <xacro:property name="left"                   value="${int(leg.startswith('L'))*2-1}"/>

    <xacro:if value="${leg_config=='xx'}">
      <xacro:property name="front" value="${int(leg.startswith('F', 1))*2-1}"/>
    </xacro:if>
    <xacro:if value="${leg_config=='xo'}">
      <xacro:property name="front" value="1"/>
    </xacro:if>
    <xacro:if value="${leg_config=='oo'}">
      <xacro:property name="front" value="${int((leg.startswith('F', 1))*2-1)*(-1)}"/>
    </xacro:if>
    <xacro:if value="${leg_config=='ox'}">
      <xacro:property name="front" value="-1"/>
    </xacro:if>

    <!-- joint shank foot -->
    <joint name="${leg}_shank_fixed_${leg}_FOOT" type="fixed">
      <parent link="${leg}_shank_fixed"/>
      <child link="${leg}_FOOT"/>
      <origin xyz="${front*S_r_SF_x} ${left*S_r_SF_y} ${S_r_SF_z}"
              rpy="0 0 0"/>
    </joint>

    <!-- Foot link -->
    <link name="${leg}_FOOT">
     <visual>
       <origin xyz="0 0 0" rpy="0 0 ${(front-1)*0.5*pi - (front*left*pi*0.25)}"/>
       <geometry>
         <mesh
             filename="package://anymal_c/urdf/leg/foot/foot_3_1_1_mesh.dae"
             scale="${anymal_meshes_scale}"/>
       </geometry>
      </visual>
      <!-- Adapter collision -->
      <collision>
        <origin xyz="0 0 ${fabs(S_r_SF_z * 0.5)}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${fabs(collision_adapter_r)}" length="${fabs(collision_adapter_l)}"/>
        </geometry>
      </collision>
      <!-- Foot collision -->
      <collision>
        <origin xyz="0 0 ${collision_foot_r*0.75}"/>
        <geometry>
          <sphere radius="${fabs(collision_foot_r)}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="${front*F_r_FFcom_x} ${left*F_r_FFcom_y} ${F_r_FFcom_z}"
                rpy="0 0 0"/>
        <mass value="${m_F}"/>
        <inertia ixx="${F_Ixx_F}" ixy="${front*left*F_Ixy_F}" ixz="${front*F_Ixz_F}"
                 iyy="${F_Iyy_F}" iyz="${left*F_Iyz_F}"       izz="${F_Izz_F}"/>
      </inertial>
    </link>

    <!-- Gazebo customization -->
    <gazebo reference="${leg}_FOOT">
      <kp>${kp}</kp>
      <kd>${kd}</kd>
      <mu1>${mu}</mu1>
      <mu2>${mu}</mu2>
    </gazebo>

  </xacro:macro>

</robot>
