- MaxDensityDataPointsFilter:
      maxDensity: 5000.0
#- MaxPointCountDataPointsFilter:
#      maxCount: 40000
# Empirically seems to work well for most environments,
# including challenging flat planes. From simulation,
# allows walking away from a building corner at least 10m
# away while still converging in real time.
- NormalSpaceDataPointsFilter:
      nbSample: 80000
