# Command.

# Message header.
Header header
# Mode.
Mode mode
# Current [A].
float64 current
# Motor position [rad].
float64 motor_position
# Motor velocity [rad/s].
float64 motor_velocity
# Gear position [rad].
float64 gear_position
# Gear velocity [rad/s].
float64 gear_velocity
# Joint position [rad].
float64 joint_position
# Joint velocity [rad/s].
float64 joint_velocity
# Joint torque [Nm].
float64 joint_torque
# PID gains [-].
float32 pid_gains_p
float32 pid_gains_i
float32 pid_gains_d
