# State.

# Message header.
Header header
# Statusword.
uint32 statusword
# Motor current [A].
float64 current
# Position of the spring on the gear side [rad].
float64 gear_position
# Velocity of the spring on the gear side [rad/s].
float64 gear_velocity
# Position of the spring on the joint side [rad].
float64 joint_position
# Velocity of the spring on the joint side [rad/s].
float64 joint_velocity
# Acceleration of the spring on the joint side [rad/s^2].
float64 joint_acceleration
# Joint torque [Nm].
float64 joint_torque
# IMU.
sensor_msgs/Imu imu
