components:
  - "ANYDRIVE_LF_HAA"
  - "ANYDRIVE_LF_HFE"
  - "ANYDRIVE_LF_KFE"
  - "ANYDRIVE_RF_HAA"
  - "ANYDRIVE_RF_HFE"
  - "ANYDRIVE_RF_KFE"
  - "ANYDRIVE_LH_HAA"
  - "ANYDRIVE_LH_HFE"
  - "ANYDRIVE_LH_KFE"
  - "ANYDRIVE_RH_HAA"
  - "ANYDRIVE_RH_HFE"
  - "ANYDRIVE_RH_KFE"
  - "OPTOFORCE_LF_FOOT"
  - "OPTOFORCE_RF_FOOT"
  - "OPTOFORCE_LH_FOOT"
  - "OPTOFORCE_RH_FOOT"
  - "ESTIMATOR"
  - "LMC"
  - "LLC"
  - "IMU"