function [figure_handler, data] = setupVisualization(data, popupmenu_contents)

figure_handler.fh = figure('Position',[100 700 900 700]);
figure_handler.ah = axes(figure_handler.fh,'Position',[0.1 0.3 0.7 0.7]);
xlabel('x');
ylabel('y');
zlabel('z');

data.figure_handler = figure_handler;
view(3);
fig_lim_min = -5;
fig_lim_max = 5;
xlim([fig_lim_min fig_lim_max]);
ylim([fig_lim_min fig_lim_max]);
zlim([fig_lim_min fig_lim_max]);
hold on; grid on;

sliders_pos_l = 150;
sliders_pos_b = 100;
sliders_pos_w = 400;
sliders_pos_h = 15;

% drop-down menu
figure_handler.dd_menu = ...
    uicontrol('Parent',figure_handler.fh,'Style','popupmenu',...
              'UserData',data,...
              'String', popupmenu_contents,...
              'Callback', {@popupmenu_cb},...
              'Position',[sliders_pos_l-100,sliders_pos_b-25,100,sliders_pos_h]);

% mass slider
figure_handler.mass_slider = ...
    uicontrol('Parent',figure_handler.fh,'Style','slider',...
              'UserData',data,...
              'Position',[sliders_pos_l,sliders_pos_b+10,sliders_pos_w,sliders_pos_h],...
              'SliderStep', [0.005, 0.01],...
              'Callback', {@slider_mass_cb},...
              'value',data.m,'min',0,'max',1);
% mass label
figure_handler.mass_slider_label = ...
    uicontrol('Style', 'text', ...
              'Parent', figure_handler.fh, ...
              'Position', [sliders_pos_l-40,sliders_pos_b+10,30,sliders_pos_h],	...
              'String', 'mass');
figure_handler.mass_slider_text = ...
    uicontrol('Style', 'text', ...
              'Parent', figure_handler.fh, ...
              'Position', [sliders_pos_l+sliders_pos_w+10,sliders_pos_b+10,40,sliders_pos_h],	...
              'String', num2str(figure_handler.mass_slider.Value));
          
% com sliders
figure_handler.vec_x_slider = ...
    uicontrol('Parent',figure_handler.fh,'Style','slider',...
              'Position',[sliders_pos_l,sliders_pos_b-sliders_pos_h,sliders_pos_w,sliders_pos_h],...
              'SliderStep', [0.005, 0.01],...
              'Callback', {@slider_cb, 1},...
              'value',0,'min',-5,'max',5);
figure_handler.vec_x_slider_text = ...
    uicontrol('Style', 'text', ...
              'Parent', figure_handler.fh, ...
              'Position', [sliders_pos_l+sliders_pos_w,sliders_pos_b-sliders_pos_h,50,sliders_pos_h],	...
              'String', '0');

figure_handler.vec_y_slider = ...
    uicontrol('Parent',figure_handler.fh,'Style','slider',...
              'Position',[sliders_pos_l,sliders_pos_b-2*sliders_pos_h,sliders_pos_w,sliders_pos_h],...
              'SliderStep', [0.005, 0.01],...
              'Callback', {@slider_cb, 2},...
              'value',0,'min',-5,'max',5);
figure_handler.vec_y_slider_text = ...
    uicontrol('Style', 'text', ...
              'Parent', figure_handler.fh, ...
              'Position', [sliders_pos_l+sliders_pos_w,sliders_pos_b-2*sliders_pos_h,50,sliders_pos_h],	...
              'String', '0');
          
figure_handler.vec_z_slider = ...
    uicontrol('Parent',figure_handler.fh,'Style','slider',...
              'Position',[sliders_pos_l,sliders_pos_b-3*sliders_pos_h,sliders_pos_w,sliders_pos_h],...
              'SliderStep', [0.005, 0.01],...
              'Callback', {@slider_cb, 3},...
              'value',0,'min',-5,'max',5);
figure_handler.vec_z_slider_text = ...
    uicontrol('Style', 'text', ...
              'Parent', figure_handler.fh, ...
              'Position', [sliders_pos_l+sliders_pos_w,sliders_pos_b-3*sliders_pos_h,50,sliders_pos_h],	...
              'String', '0');
          
name = popupmenu_contents{get(figure_handler.dd_menu, 'Value')};
vec = evalin('caller', ['data.' name ';']);
figure_handler.vec_x_slider.Value = vec(1);
figure_handler.vec_y_slider.Value = vec(2);
figure_handler.vec_z_slider.Value = vec(3);
figure_handler.vec_x_slider_text.String = num2str(vec(1));
figure_handler.vec_y_slider_text.String = num2str(vec(2));
figure_handler.vec_z_slider_text.String = num2str(vec(3));

data = drawVectors(data);

end