diagnostics:
  # percentage of the output_frequency subtracted to it
  packet_min_freq_percentage: 0.2
  # percentage of the output_frequency added to it
  packet_max_freq_percentage: 0.2
ros:
  queue_depth: 100
  frame_id: "xsens_link"
  # percentage of the output_frequency added to it
  acquisition_loop_rate_percentage: 0.5
sensor:
  device_name: "Xsens MTi"
  serial_baudrate: 921600
  queue_capacity: 3
  # time between 2 attempts to reconnect, unit: ms
  retry_interval: 500 
  # unit: ms
  max_inter_packet_time: 500 
  output_frequency: 400.0
  output_orientation: false
  correct_timing: true
  send_status_word: false
  send_sync_out_signal: false
  receive_sync_in_signal: false
  use_xsens_time: true
connection:
  retry_timeout: 1.0
synchronization:
  skip_factor: 39
  pulse_width: 2000
  #pulse width is in microseconds

  
