depth_camera_front:
  any_realsense2_camera:
    serial_no: "918512073969"
depth_camera_left:
  any_realsense2_camera:
    serial_no: "920312072337"
depth_camera_rear:
  any_realsense2_camera:
    serial_no: "920312072338"
depth_camera_right:
  any_realsense2_camera:
    serial_no: "920312071844"
load_anymal_description:
  custom_parameters:
    depth_camera_front_pitch: 30.2743
    depth_camera_front_roll: 0.49223
    depth_camera_left_pitch: 29.2429
    depth_camera_left_roll: -1.23345
    depth_camera_rear_pitch: 31.2129
    depth_camera_rear_roll: 0.511664
    depth_camera_right_pitch: 29.1659
    depth_camera_right_roll: 0.880301
    imu_roll: 0.149369154
    imu_pitch: -0.439401762
    imu_yaw: 90.0583233
stack_launcher:
  nodes:
    wide_angle_camera_front_driver:
      preprocessed_params:
        camera_info_url:
          value: 'file://$(rospack find anymal_cerberus)/config/non_ros/wide_angle_camera_calibration/front.yaml'
    wide_angle_camera_rear_driver:
      preprocessed_params:
        camera_info_url:
          value: 'file://$(rospack find anymal_cerberus)/config/non_ros/wide_angle_camera_calibration/rear.yaml'
wide_angle_camera_front:
  spinnaker_camera_nodelet:
    serial: 20032113
wide_angle_camera_rear:
  spinnaker_camera_nodelet:
    serial: 20032112
