<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Thigh -->
  <xacro:macro name="anymal_thigh" params="leg:=LF mesh_name **properties">

    <!-- Xacro:Properties -->
    <xacro:insert_block name="properties"/>

    <!-- Thigh link -->
    <xacro:property name="left"  value="${int(leg.startswith('L'))*2-1}"/>
    <xacro:property name="front" value="${int(leg.startswith('F', 1))*2-1}"/>
    <link name="${leg}_THIGH">
      <xacro:if value="$(arg mesh)">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 ${(front-1) * 0.5 * PI}"/>
          <geometry>
            <mesh filename="${mesh_name}"
                  scale="${anymal_meshes_scale}"/>
          </geometry>
        </visual>
      </xacro:if>
      <xacro:unless value="$(arg mesh)">
        <visual>
          <origin xyz="0 ${left*0.02} ${collision_l_t * -0.5}"
                  rpy="${left*0.145} 0 0"/>
          <geometry>
            <cylinder radius="${fabs(collision_r_t)}" length="${fabs(collision_l_t)}"/>
          </geometry>
          <material name="anymal_material" />
        </visual>
        <visual>
          <origin xyz="0.0 ${left * 0.07} -0.25" rpy="${PI * 0.5} 0 0"/>
          <geometry>
            <cylinder radius="${fabs(collision_r_h)}" length="${fabs(collision_l_h)}"/>
          </geometry>
          <material name="anymal_material" />
        </visual>
      </xacro:unless>
      <collision>
        <origin xyz="0 ${left*0.02} ${collision_l_t * -0.5}"
                rpy="${left*0.145} 0 0"/>
        <geometry>
          <cylinder radius="${fabs(collision_r_t)}" length="${fabs(collision_l_t)}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.0 ${left * 0.07} -0.25" rpy="${PI * 0.5} 0 0"/>
        <geometry>
          <cylinder radius="${fabs(collision_r_h)}" length="${fabs(collision_l_h)}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="${front*T_r_TTcom_x} ${left*T_r_TTcom_y} ${T_r_TTcom_z}"
                rpy="0 0 0"/>
        <mass   value="${m_T}"/>
        <inertia ixx="${T_Ixx_T}" ixy="${front*left*T_Ixy_T}" ixz="${front*T_Ixz_T}"
                 iyy="${T_Iyy_T}" iyz="${left*T_Iyz_T}" izz="${T_Izz_T}"/>
      </inertial>
    </link>

    <!-- Thigh joint -->
    <joint name="${leg}_HFE" type="revolute">
      <parent link="${leg}_HIP"/>
      <child link="${leg}_THIGH"/>
      <origin xyz="${front*H_r_HT_x}
                   ${left*H_r_HT_y}
                   ${H_r_HT_z}"/>
      <axis xyz="0 1 0"/>
      <limit effort="${t_hfe}"
        command_effort="${t_hfe_command}"
        gear_velocity="${gear_velocity}"
        current="${current}"
        lower="${-(front+1)*0.5*s_hfe_1 + (front-1)*0.5*s_hfe_2}"
        upper="${-(front-1)*0.5*s_hfe_1 + (front+1)*0.5*s_hfe_2}"
        velocity="${v_hfe}" />
      <dynamics damping="${d_hfe}" friction="${f_hfe}"/>
    </joint>

  </xacro:macro>


</robot>
