- RandomSamplingDataPointsFilter:
    prob: 0.1
- SurfaceNormalDataPointsFilter:
    knn: 10
    epsilon: 0
    keepNormals: 1
    keepDensities: 1
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter 
#- MaxDensityDataPointsFilter:
#    maxDensity: 1000.0
