# Action to send the robot into a custom joint configuration

# Define the goal
float64[] joint_positions

---

# List of available results
int8 ERROR=-2
int8 PREEMPTED=-1
int8 NA=0
int8 SUCCESS=1

# Define the result
int8 goal_reached

---

# Define a feedback message
float64 percent_complete