joint_states:
  default_positions_xx:
    - -0.1
    -  0.7
    - -1.0
    -  0.1
    -  0.7
    - -1.0
    - -0.1
    - -0.7
    -  1.0
    -  0.1
    - -0.7
    -  1.0
  default_positions_oo:
    - -0.1
    - -0.7
    -  1.0
    -  0.1
    - -0.7
    -  1.0
    - -0.1
    -  0.7
    - -1.0
    -  0.1
    -  0.7
    - -1.0
  default_positions_xo:
    - -0.13
    -  0.60
    - -1.00
    -  0.14
    -  0.62
    - -1.01
    - -0.10
    -  0.98
    - -0.98
    -  0.11
    -  0.98
    - -0.99
  default_positions_ox:
    - -0.13
    - -0.8
    -  1.6
    -  0.14
    - -0.8
    -  1.6
    - -0.10
    - -0.98
    -  0.98
    -  0.11
    - -0.98
    -  0.99