# Config file for Joy Interface with Logitech F710
##################################################

# Device name
device: myo
feedback: false
emergencyButtonIndex: 0

# Set a hard emergency stop with the button specified above?
hardEmergencyStop: false

# Mapping of the axes: each value stands for the index of the processed axis; -1 for an inactive axis.
axisMapping: [-1, 1, 3, -1, -1, -1]
# The Joy Manager interprets the axis as follows:
# [lateral, heading, roll, turning, vertical, pitch]

# Mapping of the buttons: each value stands for an index of the received buttons
buttonMapping: [-1, -1, -1, -1, -1, -1, -1, -1]

subscribers:
  joy:
    topic: /idsia/joy/arm_joy
    queue_size: 10

publishers:
  anyJoy:
    # topic is specified as launch file parameter
    queue_size: 10
    latch: false