# Config file for Joy Interface with SpaceNav
#############################################

# Device name
device: spacenav
feedback: false
emergencyButtonIndex: 0

# Set a hard emergency stop with the button specified above?
hardEmergencyStop: false

# Mapping of the axes: each value stands for an index of the received axes; -1 for an inactive axis.
axisMapping: [1, 0, 3, 5, 2, 4]
# The Joy Manager interprets the axis as follows:
# [lateral, heading, roll, turning, vertical, pitch]

# Mapping of the buttons: each value stands for an index of the received buttons
buttonMapping: [0, 1, -1, -1, -1, -1, -1, -1]

subscribers:
  joy:
    topic: joy
    queue_size: 10

publishers:
  anyJoy:
    # topic is specified as launch file parameter
    queue_size: 10
    latch: false
