# There is one important requirement on the internal frame: It's z direction must roughly correspond to gravity.
internal_frame: "map" # This frame will be used for all internal calculations. Useful for debugging, but has no further implications.
target_frame: "odom" # Quantities sent to free gait will be transformed into this frame as final step.

strategies: # List of strategies.
  - strategy:
      info: "This is a conservative strategy for climbing up stairs." # A message providing information about this strategy.
      direction: up # "up" or "down".
      default_step_parameters: # Step parameters to be used unless others are specified. Also used for approaching and recovery.
        base_linear_velocity: 0.1 # Average linear base velocity.
        base_angular_velocity: 0.2 # Average angular base velocity.
        base_height: 0.51 # Base height.
        base_support_safety_margin: 0.04 # Minimal distance of the ground-projected CoM to the support polygon edges.
        foot_linear_velocity: 0.6 # Average linear foot velocity.
        foot_trajectory_shape: square # Shape of a foot swing trajectory. Can be square, triangle, trapezoid, or straight.
        foot_step_height: 0.09 # Height of a foot swing trajectory.
        foothold_safety_margin: 0.05 # Minimal clearance of a foothold from the staircase/tread edges.
      approaching_and_recovery: # Parameters specific to approaching and recovery behavior.
        max_approach_step_size: 0.2 # Maximal length (linear distance) of an approaching step.
        max_distance_before_correction: 0.1 # Maximal foot misplacement offset before recovery behavior is triggered.
      embarking_step_sequence: # Sequence of steps after which at least two feet should be on the stairs, such that a climbing sequence can directly be appended.
        - step: # Align front legs (it is good practice to label what the steps are here for).
            name: LF # Name of the limb. Note: when climbing backwards, an automatic remapping takes place, e.g., this leg would become RH.
            target:
              tread_difference: 0 # Number of treads that should be overcome. 0 means we stay on the same tread.
              tread_origin_offset: [-0.15, 0.29, -0.01] # Foothold position w.r.t. the tread origin.
        - step:
            name: RF
            target:
              tread_difference: 0
              tread_origin_offset: [-0.15, -0.29, -0.01]
        - step: # Align hind legs.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.6, 0.29, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.6, -0.29, -0.01]
        - step: # Front legs on first tread.
            name: LF
            foot_trajectory_shape: square # Overwrite default step parameter.
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, 0.24, -0.01]
        - step:
            name: RF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, -0.34, -0.01]
        - step: # Get hind legs closer.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.45, 0.15, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.45, -0.15, -0.01]
        - step: # Front legs on second tread.
            name: LF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, 0.24, -0.01]
        - step:
            name: RF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, -0.34, -0.01]
        - step: # Hind legs into configuration for starting climbing.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.2, 0.15, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.15, -0.15, -0.01]
      climbing_step_sequence: # Sequence of steps to cycle through until the end of the stairs is reached.
        - step:
            name: LF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.05,  0.29, -0.01]
        - step:
            name: RF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, -0.29, -0.01]
        - step:
            name: LH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05,  0.15, -0.01]
        - step:
            name: RH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05, -0.15, -0.01]
      disembarking_step_sequence:
        # Step sequence for leaving the stairs after looping through the climbing step sequence.
        # It is assumed that none of the feet is yet on the platform at the end.
        - step: # Front legs climb onto the platform.
            name: LF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.1,  0.24, -0.01]
        - step:
            name: RF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.1, -0.24, -0.01]
        - step: # Hind legs climb to the second last stair.
            name: LH
            foot_trajectory_shape: trapezoid_xyz
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05,  0.15, -0.01]
        - step:
            name: RH
            foot_trajectory_shape: trapezoid_xyz
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05, -0.24, -0.01]
        - step: # Front legs move away and further onto the platform.
            name: LF
            foot_trajectory_shape: square
            target:
              tread_difference: 0
              tread_origin_offset: [0.3,  0.24, -0.02]
        - step:
            name: RF
            foot_trajectory_shape: square
            target:
              tread_difference: 0
              tread_origin_offset: [0.3, -0.24, -0.02]
        - step: # Hind legs climb to the last stair.
            name: LH
            target:
              tread_difference: 1
              foot_trajectory_shape: trapezoid_xyz
              tread_origin_offset: [-0.05,  0.24, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 1
              foot_trajectory_shape: trapezoid_xyz
              tread_origin_offset: [-0.05, -0.24, -0.01]
        - step: # Front legs move away and further onto the platform.
            name: LF
            target:
              tread_difference: 0
              tread_origin_offset: [0.6,  0.24, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 0
              tread_origin_offset: [0.6, -0.24, -0.01]
        - step: # Hind legs climb onto the platform.
            name: LH
            target:
              tread_difference: 1
              tread_origin_offset: [0.1,  0.24, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 1
              tread_origin_offset: [0.1, -0.24, -0.01]
        - step: # Front legs move away and further onto the platform.
            name: LF
            target:
              tread_difference: 0
              tread_origin_offset: [0.75,  0.24, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 0
              tread_origin_offset: [0.75, -0.24, -0.01]
        - step: # Hind legs make the final adjustment.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [0.15,  0.24, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [0.15, -0.24, -0.01]

  - strategy:
      info: "This is a conservative strategy for climbing down stairs."
      direction: down
      default_step_parameters:
        base_linear_velocity: 0.1
        base_angular_velocity: 0.2
        base_height: 0.51
        base_support_safety_margin: 0.04
        foot_linear_velocity: 0.6
        foot_trajectory_shape: triangle
        foot_step_height: 0.09
        foothold_safety_margin: 0.05
      approaching_and_recovery:
        max_approach_step_size: 0.3
        max_distance_before_correction: 0.1
      embarking_step_sequence:
        - step: # Align hind legs.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.6, 0.24, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.6, -0.24, -0.01]
        - step: # Align front legs.
            name: LF
            target:
              tread_difference: 0
              tread_origin_offset: [-0.15, 0.24, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 0
              tread_origin_offset: [-0.15, -0.24, -0.01]
        - step: # Hind legs move forward on the platform.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.5, 0.24, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.5, -0.24, -0.01]
        - step: # Front legs climb onto the first stair.
            name: LF
            target:
              tread_difference: 1
              tread_origin_offset: [0.0, 0.24, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 1
              tread_origin_offset: [0.0, -0.24, -0.01]
        - step: # Hind legs move closer to stairs on the platform.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.3, 0.24, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.3, -0.24, -0.01]
        - step: # Front legs climb down to the second stair.
            name: LF
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, 0.15, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, -0.15, -0.01]
        - step: # Hind legs make final adjustment on the platform.
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.15, 0.24, -0.01]
        - step:
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [-0.15, -0.34, -0.01]
      climbing_step_sequence: # Sequence of steps to cycle through until the end of the stairs is reached.
        - step:
            name: LF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.05,  0.15, -0.01]
        - step:
            name: RF
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.05, -0.15, -0.01]
        - step:
            name: LH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05,  0.29, -0.01]
        - step:
            name: RH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05, -0.29, -0.01]
      disembarking_step_sequence:
        # Step sequence for leaving the stairs after looping through the climbing step sequence.
        # It is assumed that none of the feet is yet on the platform at the end.
        - step: # Front legs climb down to the platform.
            name: LF
            target:
              tread_difference: 1
              tread_origin_offset: [0.2, 0.15, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 1
              tread_origin_offset: [0.2, -0.15, -0.01]
        - step: # Hind legs climb down to the second last stair.
            name: LH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05, 0.29, -0.01]
        - step:
            name: RH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05, -0.29, -0.01]
        - step: # Front legs move forward on the platform.
            name: LF
            target:
              tread_difference: 0
              tread_origin_offset: [0.3, 0.29, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 0
              tread_origin_offset: [0.3, -0.29, -0.01]
        - step: # Front legs move forward on the platform.
            name: LF
            target:
              tread_difference: 0
              tread_origin_offset: [0.55, 0.29, -0.01]
        - step:
            name: RF
            target:
              tread_difference: 0
              tread_origin_offset: [0.55, -0.29, -0.01]
        - step: # Hind legs climb down to the last stair.
            name: LH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05, 0.29, -0.01]
        - step:
            name: RH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [-0.05, -0.29, -0.01]
        - step: # Hind legs climb down to the platform.
            name: LH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.07, 0.29, -0.01]
        - step:
            name: RH
            foot_trajectory_shape: square
            target:
              tread_difference: 1
              tread_origin_offset: [0.07, -0.29, -0.01]
        - step: # Front legs make final adjustment.
            name: RF
            target:
              tread_difference: 0
              tread_origin_offset: [0.8, -0.29, -0.01]
        - step:
            name: LF
            target:
              tread_difference: 0
              tread_origin_offset: [0.8, 0.29, -0.01]
        - step: # Hind legs make final adjustment.
            name: RH
            target:
              tread_difference: 0
              tread_origin_offset: [0.15, -0.29, -0.01]
        - step:
            name: LH
            target:
              tread_difference: 0
              tread_origin_offset: [0.15, 0.29, -0.01]