- RandomSamplingDataPointsFilter:
    prob: 0.5
- MaxDistDataPointsFilter:
      maxDist: 60.0
- SurfaceNormalDataPointsFilter:
    knn: 50
    epsilon: 0
    keepNormals: 1
    keepDensities: 1
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter 
- MaxDensityDataPointsFilter:
    maxDensity: 8000.0
