#- SimpleSensorNoiseDataPointsFilter: #outputs to the console
#    sensorType: 2
- BoundingBoxDataPointsFilter:
    xMin: -0.46
    xMax: 0.46
    yMin: -0.22
    yMax: 0.22
    zMin: -0.46
    zMax: 0.44
- SamplingSurfaceNormalDataPointsFilter:
    knn: 20
    ratio: 0.6
    keepNormals: 1
    keepDensities: 1
- MaxDensityDataPointsFilter:
    maxDensity: 100
- MinDistDataPointsFilter:
    minDist: 1.0
- MaxDistDataPointsFilter:
    maxDist: 20.0
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter
