timeout_usec: 20000
self_see_links:
    - name: LF_thigh_fixed
      padding: 0.04
    - name: LF_thigh_fixed
      padding: 0.04
    - name: LF_KFE
      padding: 0.04
    - name: LF_KFE
      padding: 0.04
    - name: LF_shank_fixed
      padding: 0.12
    - name: LF_shank_fixed
      padding: 0.12
    - name: LF_FOOT
      padding: 0.04
    - name: LF_FOOT
      padding: 0.04
    - name: RF_thigh_fixed
      padding: 0.04
    - name: RF_thigh_fixed
      padding: 0.04
    - name: RF_KFE
      padding: 0.04
    - name: RF_KFE
      padding: 0.04
    - name: RF_shank_fixed
      padding: 0.12
    - name: RF_shank_fixed
      padding: 0.12
    - name: RF_FOOT
      padding: 0.04
    - name: RF_FOOT
      padding: 0.04
