timeout_usec: 20000
self_see_links:
    - name: LH_thigh_fixed
      padding: 0.04
    - name: LH_thigh_fixed
      padding: 0.04
    - name: LH_KFE
      padding: 0.04
    - name: LH_KFE
      padding: 0.04
    - name: LH_shank_fixed
      padding: 0.12
    - name: LH_shank_fixed
      padding: 0.12
    - name: LH_FOOT
      padding: 0.04
    - name: LH_FOOT
      padding: 0.04
    - name: RF_thigh_fixed
      padding: 0.04
    - name: RH_thigh_fixed
      padding: 0.04
    - name: RH_KFE
      padding: 0.04
    - name: RH_KFE
      padding: 0.04
    - name: RH_shank_fixed
      padding: 0.12
    - name: RH_shank_fixed
      padding: 0.12
    - name: RH_FOOT
      padding: 0.04
    - name: RH_FOOT
      padding: 0.04
