function c = trig_eq_kfe_c(in1,in2)
%TRIG_EQ_KFE_C
%    C = TRIG_EQ_KFE_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Jul-2017 22:04:27

S_r_SF_x = in2(1,:);
S_r_SF_y = in2(2,:);
S_r_SF_z = in2(3,:);
T_r_TS_x = in1(1,:);
T_r_TS_y = in1(2,:);
T_r_TS_z = in1(3,:);
c = S_r_SF_y.*T_r_TS_y.*2.0+S_r_SF_x.^2+S_r_SF_y.^2+S_r_SF_z.^2+T_r_TS_x.^2+T_r_TS_y.^2+T_r_TS_z.^2;
