anydrives:
- name:                     LF_HAA
  configuration_file:       configurations/LF_HAA.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         11
  ethercat_pdo_type:        A
- name:                     LF_HFE
  configuration_file:       configurations/LF_HFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         12
  ethercat_pdo_type:        A
- name:                     LF_KFE
  configuration_file:       configurations/LF_KFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         13
  ethercat_pdo_type:        A
- name:                     RF_HAA
  configuration_file:       configurations/RF_HAA.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         7
  ethercat_pdo_type:        A
- name:                     RF_HFE
  configuration_file:       configurations/RF_HFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         8
  ethercat_pdo_type:        A
- name:                     RF_KFE
  configuration_file:       configurations/RF_KFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         9
  ethercat_pdo_type:        A
- name:                     LH_HAA
  configuration_file:       configurations/LH_HAA.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         2
  ethercat_pdo_type:        A
- name:                     LH_HFE
  configuration_file:       configurations/LH_HFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         3
  ethercat_pdo_type:        A
- name:                     LH_KFE
  configuration_file:       configurations/LH_KFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         4
  ethercat_pdo_type:        A
- name:                     RH_HAA
  configuration_file:       configurations/RH_HAA.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         14
  ethercat_pdo_type:        A
- name:                     RH_HFE
  configuration_file:       configurations/RH_HFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         15
  ethercat_pdo_type:        A
- name:                     RH_KFE
  configuration_file:       configurations/RH_KFE.yaml
  ethercat_bus:             enp2s0
  ethercat_address:         16
  ethercat_pdo_type:        A

joint_position_configuration_manager:
  max_joint_velocity:       0.2

