<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Shank -->
  <xacro:macro name="anymal_adapter" params="leg:=^ mesh_name **properties">

    <!-- Xacro:Properties -->
    <xacro:insert_block name="properties"/>

    <!-- Shank link -->
    <xacro:property name="left"  value="${int(leg.startswith('L'))*2-1}"/>
    <xacro:property name="front" value="${int(leg.startswith('F', 1))*2-1}"/>
    <!-- Foot adapter link -->
    <link name="${leg}_ADAPTER">
      <xacro:if value="$(arg mesh)">
        <visual>
          <origin xyz="0 0 0"
                  rpy="0 0 ${(front-1)*0.5*PI}"/>
          <geometry>
            <mesh filename="${mesh_name}"
                  scale="${anymal_meshes_scale}"/>
          </geometry>
          <material name="anymal_material" />
        </visual>
      </xacro:if>
      <xacro:unless value="$(arg mesh)">
        <visual>
          <origin xyz="0 0 ${A_r_AM_z * 0.5}"
                  rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${fabs(collision_r_a)}" length="${fabs(A_r_AM_z)}"/>
          </geometry>
          <material name="anymal_material" />
        </visual>
      </xacro:unless>
      <collision>
        <origin xyz="0 0 ${A_r_AM_z * 0.5}"
                rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${fabs(collision_r_a)}" length="${fabs(A_r_AM_z)}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="${front*A_r_AAcom_x} ${left*A_r_AAcom_y} ${A_r_AAcom_z}"
                rpy="0 0 0"/>
        <mass value="${m_A}"/>
        <inertia ixx="${A_Ixx_A}" ixy="${front*left*A_Ixy_A}" ixz="${front*A_Ixz_A}"
                 iyy="${A_Iyy_A}" iyz="${left*A_Iyz_A}"       izz="${A_Izz_A}"/>
      </inertial>
    </link>

    <!-- Foot adapter joint ankle -->
    <joint name="${leg}_ADAPTER_JOINT" type="fixed">
      <parent link="${leg}_SHANK"/>
      <child  link="${leg}_ADAPTER"/>
      <origin xyz="${front*S_r_SA_x} ${left*S_r_SA_y} ${S_r_SA_z}"
              rpy="${left*q_SA_roll} ${front*q_SA_pitch} ${left*front*q_SA_yaw}"/>
    </joint>
  </xacro:macro>


</robot>
