adapt_coordinates:
  - transform:
      source_frame: <source_frame>
      target_frame: <target_frame>
      transform_in_source_frame:
        position: [<position_x>, <position_y>, <position_z>]
        orientation: [0.0, 0.0, <orientation_yaw>]

steps:

 # Square up.
 - step:
    - base_auto:
       height: 0.48
 - step:
    - base_auto:
    - footstep:
       name: LH_LEG
       target:
        frame: <source_frame>
        position: [-0.2, 0.24, 0.0]
 - step:
    - base_auto:
 - step:
    - base_auto:
    - footstep:
       name: LF_LEG
       target:
        frame: <source_frame>
        position: [0.35, 0.24, 0.0]
 - step:
    - base_auto:
 - step:
    - base_auto:
    - footstep:
       name: RH_LEG
       target:
        frame: <source_frame>
        position: [-0.2, -0.24, 0.0]
 - step:
    - base_auto:
 - step:
    - base_auto:
    - footstep:
       name: RF_LEG
       target:
        frame: <source_frame>
        position: [0.35, -0.24, 0.0]

 # Prepare hind legs.
 - step:
   - base_auto:
      height: 0.48
      average_linear_velocity: <average_velocity>
 - step:
    - base_auto:
    - footstep:
       name: LH_LEG
       target:
        frame: <source_frame>
        position: [0.05, 0.24, 0.0]
 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
    - base_auto:
    - footstep:
       name: RH_LEG
       target:
        frame: <source_frame>
        position: [0.05, -0.24, 0.0]

 # Step over with fore legs.
 - step:
   - base_auto:
      height: 0.44
      support_margin: 0.06
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: RF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0.0, deg(220), deg(-240)]
 - step:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [0.80, -0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>
 - step:
   - base_auto:
      support_margin: 0.06
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: LF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0, deg(220), deg(-240)]
 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [0.80, 0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>

 # Turn hind legs to O-configuration.
 - step:
   - base_auto:
      height: 0.49
      support_margin: 0.06
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: LH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0.0, deg(-280), deg(280)]
 - step:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [0.05, 0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>
 - step:
   - base_auto:
      support_margin: 0.06
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: RH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0.0, deg(-280), deg(280)]
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [0.05, -0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>

 # Sneak half ways.
 - step:
    - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [0.1, 0.24, 0.0]
      average_velocity: <average_velocity>
 - step:
    - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [0.95, 0.24, 0.0]
      average_velocity: <average_velocity>

 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [0.2, -0.24, 0.0]
      average_velocity: <average_velocity>
 - step:
    - base_auto:
       average_linear_velocity: <average_velocity>
 - step:
   - base_auto:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [1.05, -0.24, 0.0]
      average_velocity: <average_velocity>
 - step:
    - base_auto:
       average_linear_velocity: <average_velocity>
 - step:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [0.35, 0.24, 0.0]
      average_velocity: <average_velocity>
 - step:
    - base_auto:
       average_linear_velocity: <average_velocity>
 - step:
   - base_auto:
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [1.15, 0.24, 0.0]
      average_velocity: <average_velocity>
 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [0.35, -0.24, 0.0]
      average_velocity: <average_velocity>
 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
   - base_auto:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [1.15, -0.24, 0.0]
      average_velocity: <average_velocity>

 # Switch front legs back to normal.
 - step:
   - base_auto:
      height: 0.49
      support_margin: 0.1
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: RF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0.0, deg(80), deg(-130)]
 - step:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [1.15, -0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>
 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: LF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0.0, deg(80), deg(-130)]
 - step:
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [1.15, 0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>

 # Step over with hind legs.
 - step:
   - base_auto:
      height: 0.40
      support_margin: 0.12
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: LH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0.0, deg(-110), deg(110)]
 - step:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [0.85, 0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>
 - step:
   - base_auto:
      average_linear_velocity: <average_velocity>
 - step:
   - joint_trajectory:
      name: RH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 5.0
           positions: [0.0, deg(-90), deg(100)]
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [0.85, -0.24, 0.0]
      profile_type: straight
      average_velocity: <average_velocity>
 - step:
   - base_auto:
      height: 0.48
      average_linear_velocity: <average_velocity>

# Finish with front legs
 - step:
    - base_auto:
 - step:
   - base_auto:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [1.4, -0.24, 0.0]
 - step:
    - base_auto:
 - step:
   - base_auto:
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [1.4, 0.24, 0.0]
 - step:
   - base_auto:
