adapt_coordinates:
  - transform:
      source_frame: <source_frame>
      target_frame: <target_frame>
      transform_in_source_frame:
        position: [<position_x>, <position_y>, <position_z>]
        orientation: [0.0, 0.0, <orientation_yaw>]

steps:

 # Prepare hind legs.
 - step:
   - base_auto:
      height: 0.47
 - step:
    - base_auto:
    - footstep:
       name: LH_LEG
       target:
        frame: <source_frame>
        position: [-0.1, 0.27, 0.0]
 - step:
   - base_auto:
 - step:
    - base_auto:
    - footstep:
       name: RH_LEG
       target:
        frame: <source_frame>
        position: [-0.1, -0.27, 0.0]

 # Step up with fore legs.
 - step:
   - base_auto:
      height: 0.44
 - step:
   - joint_trajectory:
      name: RF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 3.0
           positions: [deg(15), deg(150), deg(-180)]
         - time: 6.0
           positions: [deg(-15), deg(220), deg(-240)]
 - step:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [0.8, -0.27, <step_height>]
      profile_type: straight

 - step:
   - base_auto:
 - step:
   - joint_trajectory:
      name: LF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 3.0
           positions: [deg(-15), deg(150), deg(-180)]
         - time: 6.0
           positions: [deg(15), deg(220), deg(-240)]
 - step:
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [0.8, 0.27, <step_height>]
      profile_type: straight

 # Turn hind legs to O-configuration.
 - step:
   - base_auto:
      height: 0.46
 - step:
   - joint_trajectory:
      name: LH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 3.0
           positions: [deg(-15), deg(-150), deg(220)]
         - time: 6.0
           positions: [deg(15), deg(-280), deg(280)]
 - step:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [-0.1, 0.27, 0.0]
      profile_type: straight
 - step:
   - base_auto:
 - step:
   - joint_trajectory:
      name: RH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 3.0
           positions: [deg(15), deg(-150), deg(220)]
         - time: 6.0
           positions: [deg(-15), deg(-280), deg(280)]
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [-0.1, -0.27, 0.0]
      profile_type: straight

 # Sneak half ways.
 - step:
    - base_auto:
       height: 0.39
 - step:
   - base_auto:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [0.95, -0.27, <step_height>]
 - step:
    - base_auto:
 - step:
   - base_auto:
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [0.95, 0.27, <step_height>]
 - step:
    - base_auto:
 - step:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [0.12, 0.27, 0.0]
 - step:
   - base_auto:
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [0.12, -0.27, 0.0]
 - step:
    - base_auto:
 - step:
   - base_auto:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [1.1, -0.27, <step_height>]
 - step:
    - base_auto:
 - step:
   - base_auto:
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [1.1, 0.27, <step_height>]
 - step:
    - base_auto:
 - step:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [0.3, 0.27, 0.0]
 - step:
   - base_auto:
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [0.3, -0.27, 0.0]

 # Switch front legs back to normal.
 - step:
   - base_auto:
      height: 0.48
 - step:
   - joint_trajectory:
      name: RF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 3.0
           positions: [deg(15), deg(150), deg(-180)]
         - time: 6.0
           positions: [deg(-15), deg(80), deg(-130)]
 - step:
   - footstep:
      name: RF_LEG
      target:
       frame: <source_frame>
       position: [1.0, -0.29, <step_height>]
      profile_type: straight

 - step:
   - base_auto:
 - step:
   - joint_trajectory:
      name: LF_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 3.0
           positions: [deg(-15), deg(150), deg(-180)]
         - time: 6.0
           positions: [deg(15), deg(80), deg(-130)]
 - step:
   - footstep:
      name: LF_LEG
      target:
       frame: <source_frame>
       position: [1.05, 0.27, <step_height>]
      profile_type: straight


 # Step up with hind legs.
 - step:
   - base_auto:
      height: 0.48
 - step:
   - joint_trajectory:
      name: LH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 4.0
           positions: [deg(-15), deg(-150), deg(180)]
         - time: 6.0
           positions: [0.0, deg(-90), deg(165)]
 - step:
   - base_auto:
   - footstep:
      name: LH_LEG
      target:
       frame: <source_frame>
       position: [0.6, 0.22, <step_height>]
      profile_type: straight
 - step:
   - base_target:
      target:
        frame: <source_frame>
        position: [0.85, 0.04, 0.45]
        orientation: [0.0, 0.0, 0.0]
 - step:
   - joint_trajectory:
      name: RH_LEG
      ignore_contact: true
      trajectory:
       joint_names: [HAA, HFE, KFE]
       knots:
         - time: 4.0
           positions: [deg(15), deg(-150), deg(180)]
         - time: 6.0
           positions: [0.0, deg(-90), deg(165)]
 - step:
   - footstep:
      name: RH_LEG
      target:
       frame: <source_frame>
       position: [0.6, -0.22, <step_height>]
      profile_type: straight
 - step:
   - base_auto:
      height: 0.46
