anymal_highlevel_controller:
  motion_transitioner:
    motion_states:
      gap_climb_down:
        direct_transit_state: square_up
      gap_climb_up:
        direct_transit_state: square_up
    transitions:
      gap_climb_down:
        connections:
          square_up: 30.0
        motion:
          motion_controller: free_gait
          operation_mode: gap_climb_down
          reference_type: action
        preempt_state: _preempted
        target_state: gap_climb_down
      gap_climb_up:
        connections:
          square_up: 30.0
        motion:
          motion_controller: free_gait
          operation_mode: gap_climb_up
          reference_type: action
        preempt_state: _preempted
        target_state: gap_climb_up
free_gait_action_loader:
  free_gait_action_packages:
    priority_99: sandbox_data
stack_launcher:
  nodes:
    anymal_highlevel_controller:
      preprocessed_params:
        staircase_description_folder_path:
          value: $(rospack find sandbox_data)/staircase_descriptions
    gazebo:
      preprocessed_params:
        roslaunch_args:
          value: --verbose -e ode $(rospack find sandbox_data)/worlds/playground.world
        roslaunch_env_args_gazebo_model_path:
          value: $(rospack find sandbox_data)/..
    gazebo2marker:
      preprocessed_params:
        roslaunch_env_arg_gazebo_model_path:
          value: $(rospack find sandbox_data)/..
        roslaunch_env_args_mesh_workspace_path:
          value: $(rospack find sandbox_data)/..
    gazebo2tf:
      preprocessed_params:
        roslaunch_env_arg_gazebo_model_path:
          value: $(rospack find sandbox_data)/..
        roslaunch_env_args_mesh_workspace_path:
          value: $(rospack find sandbox_data)/..
    path_planning_and_following:
      preprocessed_params:
        waypoints_file_path:
          value: $(rospack find sandbox_data)/waypoints/playground.json
    slam:
      preprocessed_params:
        mapping_load_map_on_launch_file:
          value: $(rospack find sandbox_data)/point_clouds/playground.pb
    slam_map_loader:
      preprocessed_params:
        mapping_load_map_on_launch_file:
          value: $(rospack find sandbox_data)/point_clouds/playground.pb
    spawn_anymal:
      roslaunch:
        args: -param anymal_simulation_description -urdf -model anymal -x 0.0 -y 0.0 -z 0.8 -R 0.0 -P 0.0 -Y 0.0
    rqt_gui:
      preprocessed_params:
        behavior_engine_environment_mission_folder:
          key: /rqt_behavior_engine/mission_folders/environment
          value: $(rospack find sandbox_data)/missions/playground
        state_machine_editor_default_path:
          value: $(rospack find sandbox_data)/missions/playground/NewMission.yaml
    rviz_world_loader:
      preprocessed_params:
        world_file:
          value: $(rospack find sandbox_data)/rviz/playground.yaml
    waypoints_editor:
      preprocessed_params:
        default_path:
          value: $(rospack find sandbox_data)/waypoints/playground.json
