anymal_lowlevel_controller:
  anydrive_setup:
    anydrives:
      LF_HAA:
        communication:
          bus: enp5s0
        configuration:
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 15.0
                i: 0.08
                p: 4.5
      LF_HFE:
        communication:
          bus: enp5s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
      LF_KFE:
        communication:
          bus: enp5s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
      LH_HAA:
        communication:
          bus: enp2s0
        configuration:
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 15.0
                i: 0.08
                p: 4.5
      LH_HFE:
        communication:
          bus: enp2s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
      LH_KFE:
        communication:
          bus: enp2s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
      RF_HAA:
        communication:
          bus: enp4s0
        configuration:
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 15.0
                i: 0.08
                p: 4.5
      RF_HFE:
        communication:
          bus: enp4s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
      RF_KFE:
        communication:
          bus: enp4s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
      RH_HAA:
        communication:
          bus: enp1s0
        configuration:
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 15.0
                i: 0.08
                p: 4.5
      RH_HFE:
        communication:
          bus: enp1s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
      RH_KFE:
        communication:
          bus: enp1s0
        configuration:
          fan:
            lower_temperature: 35.0
            upper_temperature: 40.0
          max_freeze_current: 5.0
          modes:
            joint_position:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_position_velocity_torque:
              gains:
                d: 0.25
                i: 0.5
                p: 80.0
            joint_torque:
              gains:
                d: 20.0
                i: 0.12
                p: 5.0
rpsm_apc:
  password: beaver
rpsm_lpc:
  password: beaver
  port: /dev/ttyS4
rpsm_npc:
  password: beaver
stack_launcher:
  nodes:
    load_anymal_description:
      preprocessed_params:
        xacro_file:
          value: $(rospack find anymal_beaver)/urdf/anymal.urdf.xacro
